NUM_GPUS: 1 #使用8块GPU进行训练
TRAIN:
  ENABLE: True #启用训练模式
  MAX_EPOCH: 20 #训练总轮数为20个epoch
  CHECKPOINT_PERIOD: 1 #每1个epoch保存一次模型检查点
  CHECKPOINT_EPOCH_RESET: True #重置检查点的轮次
TEST:
  ENABLE: True #启用测试模式


DATASET:
  NAME: CelebDF
  DATASET_NAME: CelebDF  # 数据集名称
  ROOT_DIR: /root/autodl-tmp/celeb-df-v2-img  # 数据集根目录
  TRAIN_INFO_TXT: '/root/autodl-tmp/splits-img/train.txt'  # 训练集信息文件
  VAL_INFO_TXT: '/root/autodl-tmp/splits-img/eval.txt'  # 验证集信息文件
  TEST_INFO_TXT: '/root/autodl-tmp/splits-img/test.txt'  # 测试集信息文件
  IMG_SIZE: 380  # 图像大小
  SCALE_RATE: 1.0  # 图像缩放比例
  ROTATE_ANGLE: 10 #图像旋转角度
  CUTOUT_H: 10 #图像旋转角度
  CUTOUT_W: 10 #随机遮挡宽度
  COMPRESSION_LOW: 65 #图像压缩最低质量
  COMPRESSION_HIGH: 80 #图像压缩最低质量
  # 简化数据增强配置
  AUGMENTATIONS:
    TRAIN:
      - Resize:
          height: 320
          width: 320
    TEST:
      - Resize:
          height: 320
          width: 320
DATALOADER:
  BATCH_SIZE: 8 #每个批次的样本数
  NUM_WORKERS: 4  #数据加载的进程数
LOSS:
  LOSS_FUN: FocalLoss #使用Focal Loss作为损失函数
  LOSS_WEIGHT: 1 #损失权重
  logits: True #使用模型的原始输出
MODEL:
  MODEL_NAME: M2TR #模型名称
  PRETRAINED: 'imagenet'  #使用ImageNet预训练权重
  ESCAPE: '' #转义字符（此处为空）
  IMG_SIZE: 320 #图像大小
  BACKBONE: efficientnet-b4 #使用EfficientNet-B4作为主干网络
  DEPTH: 4 #网络深度
  TEXTURE_LAYER: b2 #纹理特征层
  FEATURE_LAYER: final #特征提取层
  NUM_CLASSES: 2 #分类数（二分类：真实/伪造）
  DROP_RATIO: 0.5  #随机失活比例
  HAS_DECODER: False #是否使用解码器
OPTIMIZER:
  OPTIMIZER_METHOD: sgd #使用随机梯度下降优化器
  BASE_LR: 0.0005 #基础学习率
  EPS: 0.00000001 #数值稳定性参数
  MOMENTUM: 0.9 #动量
